name: "Terraform-Dev"
on:
  push:
    branches:
      - main
jobs:
  terraform-dev:
    name: 'Terraform-Dev'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
      TF_VAR_user_ocid:    ${{ secrets.OCI_USER_OCID }}
      TF_VAR_private_key:  ${{ secrets.OCI_PRIVATE_KEY }}
      TF_VAR_fingerprint:  ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_region:       ${{ secrets.OCI_REGION }}
      TF_VAR_env:          ${{ secrets.DEVELOPMENT_ENV_NAME }}
      TF_VAR_testing_compartment_ocid: ${{ secrets.OCI_TESTING_COMPARTMENT_OCID }}
      TF_VAR_subnet_ocid: ${{ secrets.OCI_SUBNET_OCID }}
      TF_VAR_testing_load_balancer_ocid: ${{ secrets.OCI_TESTING_LOAD_BALANCER_OCID }}
      TF_VAR_management_compartment_ocid: ${{ secrets.OCI_MANAGEMENT_COMPARTMENT_OCID }}
      TF_VAR_ec_service_compartment_ocid: ${{ secrets.OCI_EC_SERVICE_COMPARTMENT_OCID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd ./env/dev
          terraform init

      - name: Terraform Plan
        run: |
          cd ./env/dev
          terraform plan -out=tfplan

      # - name: Terraform Apply
      #   run: |
      #     cd ./env/dev
      #     terraform apply -auto-approve tfplan

      # - name: Terraform Plan Destroy
      #   run: |
      #     cd ./env/dev
      #     terraform plan -destroy -out=tfplan

      # - name: Terraform Destroy
      #   run: |
      #     cd ./env/dev
      #     terraform destroy -auto-approve