name: "Terraform-Check"

on:
    workflow_dispatch:
    push:
        branches:
            - "feature/**" # ローカルのfeatureブランチからpushされた場合

# コミット作成のための権限
permissions:
    contents: write

jobs:
    terraform-check:
        name: "Terraform-Check"
        runs-on: ubuntu-latest
        env:
            TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
            TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
            TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
            TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
            TF_VAR_region: ${{ secrets.OCI_REGION }}
        steps:
            # リポジトリのチェックアウト
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # Terraformのセットアップ
            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v3

            # TFLintのセットアップ
            - name: TFLint Setup
              uses: terraform-linters/setup-tflint@v4
              with:
                  tflint_version: latest

            # TFLintの初期化
            - name: TFLint Init
              run: tflint --init
              env:
                  GITHUB_TOKEN: ${{ github.token }}

            # TFLintによる静的解析
            - name: Run TFLint
              run: tflint --recursive --config=$(realpath .tflint.hcl) --format compact

            # terraform fmtコマンドによるフォーマットチェック
            - name: Terraform Format Check
              run: terraform fmt -diff -recursive

            # フォーマット修正時のコミットを作成
            - name: Commit add terraform fmt
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                  commit_message: "add:terraform fmt"
                  file_pattern: "**/*.tf"
